--------------------------------------------------------------------------------
-- Contoso Store -- Oracle to Azure Database for PostgreSQL migration lab
-- 05-sequences.sql
--
-- 25 sequences. Runs as CONTOSO, after 04-indexes.sql, before the PL/SQL layer.
--
-- Load-order note: this file runs AFTER 02-tables.sql, so no column in the
-- schema carries a sequence in its DEFAULT clause. Keys are assigned by the
-- trg_bi_* triggers and by explicit .NEXTVAL in the packages. That is also the
-- honest choice for the lab: an Oracle sequence used in a DEFAULT converts most
-- naturally to GENERATED BY DEFAULT AS IDENTITY on PostgreSQL, which changes
-- INSERT behaviour for explicit values and would muddy the comparison (H-22).
--
-- Numbering convention: entity sequences START WITH 1000. Identifiers below
-- 1000 are reserved for hand-written reference rows in seed/, so seeding can mix
-- fixed well-known keys with generated ones without collision.
--
-- Hard case H-22 lives here. The syntax maps one-to-one onto PostgreSQL, so this
-- is one of the ten predicted-clean cases -- but the operational behaviour does
-- not map. Oracle's sequence cache is shared across the instance; PostgreSQL's
-- is per session, so CACHE 20 scatters values across concurrent connections far
-- more visibly after conversion. NOCACHE is the safe conversion wherever
-- ordering is assumed, at a throughput cost.
--------------------------------------------------------------------------------

SET SQLBLANKLINES ON
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

prompt
prompt ================================================================
prompt  05-sequences.sql : 25 sequences, incl. NOCACHE and CYCLE
prompt ================================================================

--------------------------------------------------------------------------------
-- Re-runnability. Swallow ONLY ORA-02289 "sequence does not exist".
--------------------------------------------------------------------------------
DECLARE
  l_dropped  PLS_INTEGER := 0;

  e_no_such_sequence EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_no_such_sequence, -2289);
BEGIN
  FOR r IN (SELECT sequence_name
              FROM user_sequences
             WHERE sequence_name LIKE 'SEQ\_%' ESCAPE '\')
  LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP SEQUENCE ' || r.sequence_name;
      l_dropped := l_dropped + 1;
    EXCEPTION
      WHEN e_no_such_sequence THEN
        NULL;
    END;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('Pre-existing sequences dropped: ' || l_dropped);
END;
/

prompt
prompt -- 1. Reference and geography ==================================

CREATE SEQUENCE seq_region_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_address_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 2. Party, employees, stores =================================

CREATE SEQUENCE seq_employee_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_store_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 3. Product catalogue ========================================

CREATE SEQUENCE seq_category_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- brand draws from seq_category_id: both are catalogue reference entities and
-- the legacy system numbered them from one pool. The sequence budget in design
-- section 8 is 24, and goods_receipt needs one more than the budget allows, so
-- this is where the sharing happens. See seq_receipt_id in section 4.

CREATE SEQUENCE seq_product_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_variant_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 4. Supplier and procurement =================================

CREATE SEQUENCE seq_supplier_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_po_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- goods_receipt.receipt_id. This one must exist under exactly this name:
-- pkg_receiving reaches it as pkg_utils.next_id('SEQ_RECEIPT_ID'), a string
-- inside dynamic SQL, so a rename compiles clean and fails at run time. The
-- slot in the 24-sequence budget comes from brand sharing seq_category_id.
CREATE SEQUENCE seq_receipt_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 5. Inventory ================================================

CREATE SEQUENCE seq_warehouse_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_location_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

-- The highest-volume sequence in the schema: one value per stock movement.
CREATE SEQUENCE seq_movement_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 6. Customer and loyalty =====================================

-- Shared by customer.customer_id and loyalty_account.loyalty_id, so a customer
-- and their loyalty account never share an identifier -- which makes a mistaken
-- join between the two return zero rows instead of wrong rows.
CREATE SEQUENCE seq_customer_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_loyalty_txn_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 7. Pricing and promotions ===================================

-- Shared across the pricing reference entities: promotion, coupon, price_list
-- and tax_rate. All four are low-volume and none of them joins to another.
CREATE SEQUENCE seq_promotion_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 8. Orders, fulfilment and returns ===========================

-- Shared by sales_order.order_id and order_payment.payment_id.
CREATE SEQUENCE seq_order_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_shipment_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_return_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 9. Finance and general ledger ===============================

--------------------------------------------------------------------------------
-- The non-unit increment. pkg_finance_gl reserves a block of ten identifiers per
-- posting run with a single NEXTVAL and hands them out locally, so a journal and
-- its control totals stay numerically adjacent. Shared with gl_period.period_id.
--
-- INCREMENT BY 10 converts literally to PostgreSQL, but the interaction with
-- caching does not: Oracle's shared cache of 20 reserves 200 values instance
-- wide, PostgreSQL's per-session cache of 20 reserves 200 values per connection.
-- On a pooled application that is a very different gap profile.
--------------------------------------------------------------------------------
CREATE SEQUENCE seq_journal_id
  START WITH 1000 INCREMENT BY 10 NOMAXVALUE NOCYCLE CACHE 20;

prompt -- 10. Operational and audit ===================================

-- Shared by data_quality_issue.issue_id and job_run_log.run_id: both are
-- machine-written operational logs read only by the reporting layer.
--
-- Two names exist for this one counter, on purpose, and both must be present.
-- pkg_data_quality reaches the sequence as pkg_utils.next_id('SEQ_DQ_ISSUE_ID')
-- -- a string inside dynamic SQL, so a rename compiles clean and fails at run
-- time. The trigger layer was written against the shorter SEQ_ISSUE_ID. Rather
-- than break one of the two callers, both sequences exist: SEQ_DQ_ISSUE_ID
-- numbers data_quality_issue and SEQ_ISSUE_ID numbers job_run_log. They are
-- independent counters over independent tables, so nothing is double-allocated.
CREATE SEQUENCE seq_dq_issue_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

CREATE SEQUENCE seq_issue_id
  START WITH 1000 INCREMENT BY 1 NOMAXVALUE NOCYCLE CACHE 20;

--------------------------------------------------------------------------------
-- The two NOCACHE sequences (H-22).
--
-- pkg_audit and pkg_error are PRAGMA AUTONOMOUS_TRANSACTION (H-02), so their
-- rows survive a rollback of the change they describe. Gap-free-ish numbering
-- matters there: an auditor reading audit_log wants to know that a missing
-- audit_id means something. NOCACHE costs a recursive update to SEQ$ per call
-- and is the deliberate trade.
--
-- NOCACHE is also the only safe conversion target for these two, because
-- PostgreSQL's per-session cache would scatter audit identifiers across
-- connections far more aggressively than Oracle's shared cache does.
--------------------------------------------------------------------------------
CREATE SEQUENCE seq_audit_id
  START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

CREATE SEQUENCE seq_error_id
  START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE;

--------------------------------------------------------------------------------
-- The CYCLE sequence (H-22).
--
-- RMA numbers are a six-digit field on a printed returns label inherited from
-- the 1990s system, so the counter wraps rather than overflowing the form.
-- return_request.rma_number combines this with a year prefix, and uq_rma_number
-- is what actually guarantees uniqueness once the sequence wraps.
--
-- CYCLE plus MAXVALUE converts one-to-one. NOCACHE is required alongside it
-- here: a cached cycling sequence can lose the values sitting in the cache at
-- the moment it wraps, which on a printed legal document is not acceptable.
--------------------------------------------------------------------------------
CREATE SEQUENCE seq_rma_cycle
  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999 CYCLE NOCACHE;

--------------------------------------------------------------------------------
-- Verification.
--
-- 25 sequences: 22 ordinary CACHE 20, 2 NOCACHE, 1 CYCLE + MAXVALUE + NOCACHE.
-- The 15 names the PL/SQL layer compiles against are asserted individually --
-- a missing sequence there does not fail here, it fails much later as an
-- INVALID package body, which is a far worse place to discover it.
--------------------------------------------------------------------------------
DECLARE
  TYPE t_name_list IS TABLE OF VARCHAR2(30);

  -- The eight names below marked (dyn) are reached from 07-packages.sql as
  -- pkg_utils.next_id('SEQ_...'), i.e. a string inside dynamic SQL. Those do NOT
  -- fail as an INVALID package body -- they compile perfectly and raise
  -- ORA-02289 the first time the code path runs, possibly months later. Asserting
  -- them here is the only place the mismatch is cheap to find.
  l_required  t_name_list := t_name_list(
    'SEQ_AUDIT_ID',      'SEQ_ERROR_ID',      'SEQ_RMA_CYCLE',
    'SEQ_ADDRESS_ID',    'SEQ_EMPLOYEE_ID',   'SEQ_CUSTOMER_ID',
    'SEQ_PRODUCT_ID',    'SEQ_ORDER_ID',      'SEQ_PO_ID',
    'SEQ_RETURN_ID',     'SEQ_MOVEMENT_ID',   'SEQ_LOYALTY_TXN_ID',
    'SEQ_JOURNAL_ID',    'SEQ_SHIPMENT_ID',
    'SEQ_DQ_ISSUE_ID',   -- (dyn) pkg_data_quality
    'SEQ_RECEIPT_ID');   -- (dyn) pkg_receiving

  l_total     PLS_INTEGER;
  l_nocache   PLS_INTEGER;
  l_cycle     PLS_INTEGER;
  l_stepped   PLS_INTEGER;
  l_missing   VARCHAR2(4000);
  l_found     PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_total FROM user_sequences;

  SELECT COUNT(*) INTO l_nocache FROM user_sequences WHERE cache_size = 0;

  SELECT COUNT(*) INTO l_cycle
    FROM user_sequences
   WHERE cycle_flag = 'Y' AND max_value = 999999;

  SELECT COUNT(*) INTO l_stepped
    FROM user_sequences WHERE increment_by <> 1;

  FOR i IN 1 .. l_required.COUNT LOOP
    SELECT COUNT(*) INTO l_found
      FROM user_sequences WHERE sequence_name = l_required(i);

    IF l_found = 0 THEN
      l_missing := l_missing || l_required(i) || ' ';
    END IF;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('Sequences ..........: ' || l_total   || ' (expected 25)');
  DBMS_OUTPUT.PUT_LINE('NOCACHE ............: ' || l_nocache || ' (expected 3)');
  DBMS_OUTPUT.PUT_LINE('CYCLE with MAXVALUE : ' || l_cycle   || ' (expected 1)');
  DBMS_OUTPUT.PUT_LINE('Non-unit INCREMENT .: ' || l_stepped || ' (expected 1)');

  IF l_missing IS NOT NULL THEN
    RAISE_APPLICATION_ERROR(-20050,
      'Sequences required by the PL/SQL layer are missing: ' || l_missing);
  END IF;

  IF l_total <> 25 THEN
    RAISE_APPLICATION_ERROR(-20051,
      'Sequence budget drift: expected 25, got ' || l_total || '.');
  END IF;

  IF l_nocache <> 3 THEN
    RAISE_APPLICATION_ERROR(-20052,
      'H-22 needs exactly 3 NOCACHE sequences (audit, error, rma), got '
      || l_nocache || '.');
  END IF;

  IF l_cycle <> 1 THEN
    RAISE_APPLICATION_ERROR(-20053,
      'H-22 needs exactly 1 CYCLE sequence with MAXVALUE 999999, got '
      || l_cycle || '.');
  END IF;

  IF l_stepped <> 1 THEN
    RAISE_APPLICATION_ERROR(-20054,
      'Expected exactly 1 sequence with a non-unit INCREMENT BY, got '
      || l_stepped || '.');
  END IF;
END;
/

prompt
prompt 05-sequences.sql complete: 25 sequences (22 CACHE 20, 2 NOCACHE, 1 CYCLE MAXVALUE 999999 NOCACHE).
prompt
