-- =====================================================================================
-- Contoso Store -- Oracle source schema
-- 09-triggers.sql : every trigger timing Oracle offers
-- =====================================================================================
-- Owner        : CONTOSO
-- Depends on   : core + operational tables, 06-views.sql, 07-packages.sql,
--                08-procedures.sql
-- Exercises    : H-25 all timings, H-26 compound triggers, H-27 INSTEAD OF,
--                H-02 autonomous audit from a trigger, H-22 CYCLE sequence,
--                H-10 FORALL from a trigger, H-17 virtual columns, H-31 DECODE/NVL,
--                H-37 TSLTZ, H-38 empty string, T-09 SYSDATE
--
-- Design contract: docs/design.md section 6.4 -- 26 triggers.
--
-- MIGRATION NOTE (structural, applies to every trigger in this file): an Oracle trigger
-- is ONE object containing both the firing condition and the body. A PostgreSQL trigger
-- is TWO: a CREATE FUNCTION ... RETURNS TRIGGER holding the body, and a CREATE TRIGGER
-- binding it to the table. So the converted schema has roughly twice as many objects in
-- this category, the function names have to be invented (and made unique across the
-- whole schema, not just per table), and the association between a trigger and its logic
-- becomes a name convention rather than a language construct.
--
-- MIGRATION NOTE (H-25, the single most common conversion bug): a PostgreSQL BEFORE ROW
-- trigger function MUST end with RETURN NEW. If it falls off the end returning NULL, the
-- row is silently discarded -- the INSERT reports success and nothing is stored. Every
-- trg_bi_* trigger below is exposed to this. Check the generated function bodies, not
-- the trigger declarations.
-- =====================================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET DEFINE OFF
SET FEEDBACK ON

PROMPT
PROMPT ==========================================================================
PROMPT 09-triggers.sql : trigger layer
PROMPT ==========================================================================


-- =====================================================================================
-- 1-6 : BEFORE INSERT ... FOR EACH ROW -- surrogate key assignment
-- =====================================================================================
-- MIGRATION NOTE (H-22 + H-25): the "assign the key if the caller did not" pattern. On
-- PostgreSQL the idiomatic replacement is GENERATED BY DEFAULT AS IDENTITY, which removes
-- the trigger entirely -- but it also changes INSERT behaviour for explicit values and
-- for the sequence's own currval, so the lab keeps explicit sequences to avoid muddying
-- the comparison (docs/design.md H-22). If you do convert to IDENTITY, remember Oracle's
-- CACHE is instance-wide and PostgreSQL's is per session, so values scatter far more
-- visibly across concurrent connections.
-- -------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_bi_address
  BEFORE INSERT ON address
  FOR EACH ROW
BEGIN
  IF :NEW.address_id IS NULL THEN
    :NEW.address_id := pkg_utils.next_id('SEQ_ADDRESS_ID');
  END IF;
  -- normalised_key is a virtual column (H-17) and cannot be assigned here. On PostgreSQL
  -- it becomes GENERATED ALWAYS ... STORED, which also cannot be assigned -- one of the
  -- few places the two dialects agree on a restriction.
  :NEW.line1 := TRIM(:NEW.line1);
  :NEW.city  := TRIM(:NEW.city);
END trg_bi_address;
/

CREATE OR REPLACE TRIGGER trg_bi_customer
  BEFORE INSERT ON customer
  FOR EACH ROW
BEGIN
  IF :NEW.customer_id IS NULL THEN
    :NEW.customer_id := pkg_utils.next_id('SEQ_CUSTOMER_ID');
  END IF;

  IF :NEW.customer_ref IS NULL THEN
    :NEW.customer_ref := 'CU' || LPAD(TO_CHAR(:NEW.customer_id), 12, '0');
  END IF;

  -- MIGRATION NOTE (H-38): TRIM of a single-space email yields '' which Oracle stores as
  -- NULL, so the row satisfies "email IS NULL" downstream. PostgreSQL stores an empty
  -- string, the row fails that test, and the unique index on LOWER(email) starts
  -- rejecting a second blank where Oracle allowed unlimited NULLs. Nothing errors at
  -- conversion time. The first symptom is a duplicate-key error in production.
  :NEW.email := LOWER(TRIM(:NEW.email));

  IF :NEW.created_ts IS NULL THEN
    :NEW.created_ts := SYSTIMESTAMP;
  END IF;
END trg_bi_customer;
/

CREATE OR REPLACE TRIGGER trg_bi_employee
  BEFORE INSERT ON employee
  FOR EACH ROW
BEGIN
  IF :NEW.employee_id IS NULL THEN
    :NEW.employee_id := pkg_utils.next_id('SEQ_EMPLOYEE_ID');
  END IF;

  IF :NEW.employee_number IS NULL THEN
    :NEW.employee_number := 'E' || LPAD(TO_CHAR(:NEW.employee_id), 8, '0');
  END IF;

  -- full_name and is_active are virtual columns and are not assignable (H-17).
  :NEW.first_name := INITCAP(TRIM(:NEW.first_name));
  :NEW.last_name  := INITCAP(TRIM(:NEW.last_name));
END trg_bi_employee;
/

CREATE OR REPLACE TRIGGER trg_bi_supplier
  BEFORE INSERT ON supplier
  FOR EACH ROW
DECLARE
  l_contact t_contact;
BEGIN
  IF :NEW.supplier_id IS NULL THEN
    :NEW.supplier_id := pkg_utils.next_id('SEQ_SUPPLIER_ID');
  END IF;

  IF :NEW.onboarded_ts IS NULL THEN
    :NEW.onboarded_ts := SYSTIMESTAMP;
  END IF;

  -- MIGRATION NOTE (H-03): primary_contact is an object column and this calls one of its
  -- member functions. PostgreSQL sees a composite with no methods, so the converted
  -- trigger function must call a standalone is_valid_email(NEW.primary_contact). If the
  -- type converted but the methods did not, this trigger is where it surfaces -- a long
  -- way from the type definition that actually caused the failure.
  l_contact := :NEW.primary_contact;
  IF l_contact IS NOT NULL AND l_contact.is_valid_email() <> 'Y' THEN
    :NEW.is_approved := 'N';
  END IF;
END trg_bi_supplier;
/

CREATE OR REPLACE TRIGGER trg_bi_promotion
  BEFORE INSERT ON promotion
  FOR EACH ROW
BEGIN
  IF :NEW.promotion_id IS NULL THEN
    :NEW.promotion_id := pkg_utils.next_id('SEQ_PROMOTION_ID');
  END IF;

  IF :NEW.spent_amount IS NULL THEN
    :NEW.spent_amount := 0;
  END IF;

  -- MIGRATION NOTE (H-37): start_ts and end_ts are TSLTZ. This comparison runs in the
  -- session time zone, so the same INSERT can pass in London and fail in Tokyo. It is a
  -- pre-existing Oracle bug, faithfully preserved, and converting it to timestamptz
  -- preserves it again -- which is the honest outcome. Fixing it is a separate change.
  IF :NEW.end_ts <= :NEW.start_ts THEN
    RAISE_APPLICATION_ERROR(-20601, 'Promotion end_ts must be after start_ts');
  END IF;
END trg_bi_promotion;
/

CREATE OR REPLACE TRIGGER trg_bi_return_request
  BEFORE INSERT ON return_request
  FOR EACH ROW
BEGIN
  IF :NEW.return_id IS NULL THEN
    :NEW.return_id := pkg_utils.next_id('SEQ_RETURN_ID');
  END IF;

  -- MIGRATION NOTE (H-22): seq_rma_cycle is CYCLE MAXVALUE 999999 NOCACHE, so RMA
  -- numbers wrap. PostgreSQL supports CYCLE and MAXVALUE with the same spelling, so the
  -- DDL converts -- but a cycling sequence with no unique constraint behind it is a
  -- collision waiting to happen on either engine, and the NOCACHE that made Oracle's
  -- numbering near-gapless costs throughput in PostgreSQL for the same reason.
  IF :NEW.rma_number IS NULL THEN
    :NEW.rma_number := 'RMA' || TO_CHAR(SYSDATE, 'YY')
                       || LPAD(TO_CHAR(seq_rma_cycle.NEXTVAL), 6, '0');
  END IF;

  IF :NEW.requested_ts IS NULL THEN
    :NEW.requested_ts := SYSTIMESTAMP;
  END IF;
END trg_bi_return_request;
/


-- =====================================================================================
-- 7 : trg_bi_sales_order_web -- BEFORE INSERT with a WHEN clause
-- =====================================================================================
-- MIGRATION NOTE (H-25): the WHEN clause. PostgreSQL has WHEN too and the syntax is
-- nearly identical -- but note the colons: Oracle writes WHEN (NEW.channel_code = 'WEB')
-- with a bare NEW in the condition and :NEW inside the body, while PostgreSQL uses NEW in
-- both. A converter that blindly strips or adds colons breaks one or the other.
-- PostgreSQL also forbids WHEN on INSTEAD OF triggers, and forbids referencing OLD in a
-- WHEN clause on INSERT -- restrictions Oracle does not have.
-- -------------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_bi_sales_order_web
  BEFORE INSERT ON sales_order
  FOR EACH ROW
  WHEN (NEW.channel_code = 'WEB')
BEGIN
  IF :NEW.source_ip IS NULL THEN
    :NEW.source_ip := SUBSTR(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), 1, 45);
  END IF;

  IF :NEW.shipping_amount IS NULL THEN
    :NEW.shipping_amount := 0;
  END IF;

  -- Web orders never come from a named salesperson.
  :NEW.sales_employee_id := NULL;
END trg_bi_sales_order_web;
/


-- =====================================================================================
-- 8-10 : BEFORE UPDATE ... FOR EACH ROW -- stamping and gatekeeping
-- =====================================================================================

CREATE OR REPLACE TRIGGER trg_bu_app_parameter
  BEFORE UPDATE ON app_parameter
  FOR EACH ROW
BEGIN
  :NEW.updated_ts := SYSTIMESTAMP;
  -- MIGRATION NOTE (H-39): SYS_CONTEXT('USERENV','SESSION_USER') becomes session_user on
  -- PostgreSQL, which is close. The custom-namespace reads elsewhere in this schema are
  -- the problem, not this one -- see trg_aiud_customer.
  :NEW.updated_by := SUBSTR(SYS_CONTEXT('USERENV', 'SESSION_USER'), 1, 30);

  IF :OLD.is_encrypted = 'Y' AND :NEW.is_encrypted = 'N' THEN
    RAISE_APPLICATION_ERROR(-20602,
      'Parameter ' || :OLD.param_name || ' cannot be un-encrypted in place');
  END IF;
END trg_bu_app_parameter;
/

CREATE OR REPLACE TRIGGER trg_bu_product
  BEFORE UPDATE ON product
  FOR EACH ROW
BEGIN
  -- margin_pct is virtual (H-17) and is never assigned.
  IF :OLD.status = 'DISCONTINUED' AND :NEW.status = 'ACTIVE' THEN
    RAISE_APPLICATION_ERROR(-20603,
      'SKU ' || :OLD.sku || ' is discontinued and cannot be reactivated directly');
  END IF;

  IF :NEW.list_price < :NEW.unit_cost THEN
    -- Sold below cost: legal, but somebody should know.
    INSERT INTO data_quality_issue (issue_id, rule_code, entity_name, entity_key,
                                    severity, detail)
    VALUES (pkg_utils.next_id('SEQ_DQ_ISSUE_ID'), 'NEGATIVE_MARGIN', 'PRODUCT',
            :NEW.sku, 'WARN',
            'list_price ' || :NEW.list_price || ' below unit_cost ' || :NEW.unit_cost);
  END IF;
END trg_bu_product;
/

CREATE OR REPLACE TRIGGER trg_bu_store_area
  BEFORE UPDATE OF selling_area_sqm, closed_date ON store
  FOR EACH ROW
  WHEN (NEW.selling_area_sqm <> OLD.selling_area_sqm OR NEW.closed_date IS NOT NULL)
BEGIN
  -- MIGRATION NOTE (H-25 + H-38): the WHEN condition compares two possibly-NULL numbers
  -- with <>, so it is UNKNOWN -- and therefore false -- whenever either side is NULL.
  -- That is identical in PostgreSQL, which is worth stating because it looks like a bug
  -- and is not. What is NOT identical: store.legacy_migration_notes is a LONG column, and
  -- Oracle forbids referencing it through :NEW or :OLD at all (H-33). After conversion to
  -- text that restriction disappears, so a converted trigger could reference it -- and a
  -- helpful converter that "restores" the missing column reference changes behaviour.
  IF :NEW.closed_date IS NOT NULL AND :OLD.closed_date IS NULL THEN
    pkg_audit.write_audit('STORE', TO_CHAR(:OLD.store_id), 'U',
                          'closed_date=NULL',
                          'closed_date=' || TO_CHAR(:NEW.closed_date, 'YYYY-MM-DD'));
  END IF;
END trg_bu_store_area;
/


-- =====================================================================================
-- 11-13 : AFTER INSERT OR UPDATE OR DELETE ... FOR EACH ROW -- the audit trail
-- =====================================================================================
-- MIGRATION NOTE (H-02, the expensive one): these three call pkg_audit, which is
-- PRAGMA AUTONOMOUS_TRANSACTION. Converting that to a dblink self-connection means a new
-- backend connection *per row*, which is unusable on a per-row audit trigger. The
-- realistic conversion drops the autonomy and writes in the same transaction, which
-- means audit rows now roll back alongside the change they describe. That is a real
-- behaviour change with compliance implications and it needs signing off, not
-- converting. See docs/04-review-tasks.md.
-- -------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_aiud_customer
  AFTER INSERT OR UPDATE OR DELETE ON customer
  FOR EACH ROW
DECLARE
  l_action CHAR(1);
  l_pk     VARCHAR2(200);
  l_old    VARCHAR2(4000);
  l_new    VARCHAR2(4000);
BEGIN
  -- MIGRATION NOTE (H-25): INSERTING / UPDATING / DELETING become TG_OP = 'INSERT' etc.
  -- in PL/pgSQL. The conversion is mechanical; the trap is that PostgreSQL's OLD is NULL
  -- (not a record of NULLs) during INSERT, so :OLD.customer_id -> OLD.customer_id raises
  -- rather than returning NULL. Guard on TG_OP first, always.
  IF INSERTING THEN
    l_action := 'I';
    l_pk     := TO_CHAR(:NEW.customer_id);
    l_new    := :NEW.customer_ref || '|' || :NEW.last_name || '|' || :NEW.status;
  ELSIF UPDATING THEN
    l_action := 'U';
    l_pk     := TO_CHAR(:OLD.customer_id);
    l_old    := :OLD.customer_ref || '|' || :OLD.last_name || '|' || :OLD.status;
    l_new    := :NEW.customer_ref || '|' || :NEW.last_name || '|' || :NEW.status;
  ELSE
    l_action := 'D';
    l_pk     := TO_CHAR(:OLD.customer_id);
    l_old    := :OLD.customer_ref || '|' || :OLD.last_name || '|' || :OLD.status;
  END IF;

  pkg_audit.write_audit(p_table_name => 'CUSTOMER',
                        p_pk_value   => l_pk,
                        p_action     => l_action,
                        p_old_row    => l_old,
                        p_new_row    => l_new);
END trg_aiud_customer;
/

CREATE OR REPLACE TRIGGER trg_aiud_loyalty_account
  AFTER INSERT OR UPDATE OR DELETE ON loyalty_account
  FOR EACH ROW
DECLARE
  l_action CHAR(1);
  l_pk     VARCHAR2(200);
  l_old    VARCHAR2(4000);
  l_new    VARCHAR2(4000);
BEGIN
  IF INSERTING THEN
    l_action := 'I';
    l_pk     := TO_CHAR(:NEW.loyalty_id);
    l_new    := :NEW.tier_code || '|' || TO_CHAR(:NEW.points_balance);
  ELSIF UPDATING THEN
    l_action := 'U';
    l_pk     := TO_CHAR(:OLD.loyalty_id);
    l_old    := :OLD.tier_code || '|' || TO_CHAR(:OLD.points_balance);
    l_new    := :NEW.tier_code || '|' || TO_CHAR(:NEW.points_balance);
  ELSE
    l_action := 'D';
    l_pk     := TO_CHAR(:OLD.loyalty_id);
    l_old    := :OLD.tier_code || '|' || TO_CHAR(:OLD.points_balance);
  END IF;

  pkg_audit.write_audit('LOYALTY_ACCOUNT', l_pk, l_action, l_old, l_new);
END trg_aiud_loyalty_account;
/

CREATE OR REPLACE TRIGGER trg_aiud_gl_journal_line
  AFTER INSERT OR UPDATE OR DELETE ON gl_journal_line
  FOR EACH ROW
DECLARE
  l_action CHAR(1);
  l_pk     VARCHAR2(200);
BEGIN
  IF DELETING THEN
    l_action := 'D';
    l_pk     := TO_CHAR(:OLD.journal_id) || '/' || TO_CHAR(:OLD.line_no);
  ELSE
    l_action := CASE WHEN INSERTING THEN 'I' ELSE 'U' END;
    l_pk     := TO_CHAR(:NEW.journal_id) || '/' || TO_CHAR(:NEW.line_no);
  END IF;

  -- base_amount is virtual (H-17) and is readable through :NEW even though it is not
  -- writable -- an asymmetry that survives conversion to a STORED generated column.
  pkg_audit.write_audit('GL_JOURNAL_LINE', l_pk, l_action);
END trg_aiud_gl_journal_line;
/


-- =====================================================================================
-- 14-15 : the FOLLOWS pair on gl_journal_line
-- =====================================================================================
-- MIGRATION NOTE (H-25): FOLLOWS guarantees firing order between two triggers on the
-- same table at the same timing point. PostgreSQL has no FOLLOWS -- it fires triggers in
-- alphabetical *name* order. These two are named _a and _b, so they happen to convert
-- correctly by luck, and that luck is worth pointing out loudly: rename either one and
-- the order silently reverses. If order matters after conversion, encode it in the name
-- deliberately (10_, 20_ prefixes) or merge the two bodies into one trigger.
-- -------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_ar_gl_journal_line_a
  AFTER INSERT ON gl_journal_line
  FOR EACH ROW
BEGIN
  IF :NEW.debit_amount > 0 AND :NEW.credit_amount > 0 THEN
    RAISE_APPLICATION_ERROR(-20604,
      'Journal line ' || :NEW.journal_id || '/' || :NEW.line_no
      || ' may not carry both a debit and a credit');
  END IF;

  IF :NEW.fx_rate IS NULL AND :NEW.currency_code <> 'GBP' THEN
    RAISE_APPLICATION_ERROR(-20605,
      'Journal line in ' || :NEW.currency_code || ' requires an fx_rate');
  END IF;
END trg_ar_gl_journal_line_a;
/

CREATE OR REPLACE TRIGGER trg_ar_gl_journal_line_b
  AFTER INSERT ON gl_journal_line
  FOR EACH ROW
  FOLLOWS trg_ar_gl_journal_line_a
BEGIN
  -- Runs only once _a has passed its validations. On PostgreSQL that ordering is a
  -- naming coincidence.
  UPDATE gl_journal
     SET description = SUBSTR(NVL(description, 'Journal ' || :NEW.journal_id), 1, 300)
   WHERE journal_id = :NEW.journal_id
     AND status     = 'DRAFT';
END trg_ar_gl_journal_line_b;
/


-- =====================================================================================
-- 16-18 : statement-level triggers
-- =====================================================================================
-- MIGRATION NOTE (H-25): a statement-level trigger cannot see NEW or OLD in either
-- dialect -- but PostgreSQL offers something Oracle does not: transition tables, declared
-- with REFERENCING NEW TABLE AS new_rows. That is the idiomatic way to convert both these
-- statement triggers *and* the three compound triggers below, and it is usually a better
-- design than the original. The conversion is therefore an upgrade opportunity that a
-- mechanical translation will miss entirely.
-- -------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_bius_gl_period
  BEFORE INSERT OR UPDATE ON gl_period
DECLARE
  l_open NUMBER;
BEGIN
  -- Statement level, so gl_period is not mutating and can be queried freely. In a ROW
  -- trigger this same SELECT would raise ORA-04091. PostgreSQL has no mutating-table
  -- restriction at all, which means the *reason* this trigger is statement-level
  -- disappears on the target -- and so does the safety it was providing.
  SELECT COUNT(*) INTO l_open FROM gl_period WHERE status = 'OPEN';

  IF l_open > 2 THEN
    RAISE_APPLICATION_ERROR(-20606,
      'Too many OPEN GL periods (' || l_open || '); close one before opening another');
  END IF;

  DBMS_OUTPUT.PUT_LINE('trg_bius_gl_period: ' || l_open || ' period(s) currently OPEN');
END trg_bius_gl_period;
/

CREATE OR REPLACE TRIGGER trg_as_price_list_item_reprice
  AFTER DELETE ON price_list_item
DECLARE
  l_orphans NUMBER;
BEGIN
  -- A price row was removed. Anything still selling at that price is now unpriced, and
  -- the pricing cache in pkg_pricing is stale for the whole session (H-43).
  pkg_pricing.reset_cache;

  SELECT COUNT(*)
    INTO l_orphans
    FROM product_variant pv
   WHERE pv.is_active = 'Y'
     AND NOT EXISTS (SELECT 1 FROM price_list_item pli
                      WHERE pli.variant_id = pv.variant_id);

  IF l_orphans > 0 THEN
    INSERT INTO data_quality_issue (issue_id, rule_code, entity_name, entity_key,
                                    severity, detail)
    VALUES (pkg_utils.next_id('SEQ_DQ_ISSUE_ID'), 'UNPRICED_VARIANT',
            'PRODUCT_VARIANT', 'ALL', 'WARN',
            l_orphans || ' active variants have no price list entry after a delete');
  END IF;
END trg_as_price_list_item_reprice;
/

CREATE OR REPLACE TRIGGER trg_as_sales_order_line_stmt
  AFTER INSERT ON sales_order_line
BEGIN
  -- Nothing about the inserted rows is visible here -- no NEW, no OLD, no count. That is
  -- the entire teaching point: on PostgreSQL, REFERENCING NEW TABLE AS new_rows would
  -- make them visible, and this trigger could do useful work instead of announcing
  -- itself. Statement triggers are where the conversion can genuinely improve the source.
  DBMS_OUTPUT.PUT_LINE('trg_as_sales_order_line_stmt: order line batch committed at '
                       || TO_CHAR(SYSTIMESTAMP, 'HH24:MI:SS.FF3'));
END trg_as_sales_order_line_stmt;
/


-- =====================================================================================
-- 19-21 : COMPOUND TRIGGERS -- the hardest shape in the schema
-- =====================================================================================
-- MIGRATION NOTE (H-26): a compound trigger is one object with up to four timing
-- sections that share state for the duration of a single statement. It exists to dodge
-- Oracle's mutating-table error: buffer the rows as they fly past in AFTER EACH ROW, then
-- act on them in AFTER STATEMENT when the table is no longer mutating.
--
-- PostgreSQL has NO mutating-table restriction, so the entire reason for the pattern is
-- gone. The right conversion is a single FOR EACH STATEMENT trigger over a transition
-- table (REFERENCING NEW TABLE AS new_rows), which is simpler and faster than the
-- original. A *mechanical* conversion into three separate PostgreSQL triggers is broken:
-- the shared collection has nowhere to live between them, so the AFTER STATEMENT section
-- sees an empty buffer and silently does nothing. That failure produces no error, no
-- warning, and correct-looking output -- it just stops maintaining the data.
-- -------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_cmp_inventory_stock
  FOR INSERT OR UPDATE ON inventory_stock
  COMPOUND TRIGGER

  TYPE t_num IS TABLE OF NUMBER        INDEX BY PLS_INTEGER;
  TYPE t_vc  IS TABLE OF VARCHAR2(200) INDEX BY PLS_INTEGER;

  g_keys  t_vc;
  g_short t_num;
  g_n     PLS_INTEGER := 0;

  BEFORE STATEMENT IS
  BEGIN
    g_keys.DELETE;
    g_short.DELETE;
    g_n := 0;
  END BEFORE STATEMENT;

  AFTER EACH ROW IS
  BEGIN
    -- qty_available is a virtual column (H-17): readable through :NEW, never writable.
    IF :NEW.qty_available < 0 THEN
      g_n := g_n + 1;
      g_keys(g_n)  := TO_CHAR(:NEW.location_id) || '/' || TO_CHAR(:NEW.variant_id);
      g_short(g_n) := :NEW.qty_available;
    END IF;
  END AFTER EACH ROW;

  AFTER STATEMENT IS
  BEGIN
    -- MIGRATION NOTE: Oracle forbids RETURN anywhere inside a COMPOUND TRIGGER body
    -- (PLS-00678), so the usual "guard clause and bail out early" shape is not available
    -- here -- the test has to be inverted into a positive IF around the whole body. A
    -- PostgreSQL statement trigger is an ordinary function, so the converter is free to
    -- put the early RETURN back; watch that it does not also swallow the empty-buffer case.
    IF g_n > 0 THEN
      -- MIGRATION NOTE (H-10): FORALL inside a trigger. On PostgreSQL this collapses to a
      -- single INSERT ... SELECT over the transition table -- shorter, faster and clearer.
      FORALL i IN 1 .. g_n
        INSERT INTO data_quality_issue (issue_id, rule_code, entity_name, entity_key,
                                        severity, detail)
        VALUES (pkg_utils.next_id('SEQ_DQ_ISSUE_ID'), 'NEGATIVE_AVAILABLE',
                'INVENTORY_STOCK', g_keys(i), 'ERROR',
                'qty_available went negative: ' || TO_CHAR(g_short(i)));

      DBMS_OUTPUT.PUT_LINE('trg_cmp_inventory_stock: ' || g_n
                           || ' negative-availability rows recorded');
    END IF;
  END AFTER STATEMENT;

END trg_cmp_inventory_stock;
/

CREATE OR REPLACE TRIGGER trg_cmp_sales_order_line
  FOR INSERT OR UPDATE OR DELETE ON sales_order_line
  COMPOUND TRIGGER

  TYPE t_num IS TABLE OF NUMBER INDEX BY PLS_INTEGER;

  g_variant t_num;
  g_loc     t_num;
  g_qty     t_num;
  g_n       PLS_INTEGER := 0;

  BEFORE STATEMENT IS
  BEGIN
    g_variant.DELETE;
    g_loc.DELETE;
    g_qty.DELETE;
    g_n := 0;
  END BEFORE STATEMENT;

  AFTER EACH ROW IS
    l_delta NUMBER;
  BEGIN
    -- Reserve on insert, release on delete, adjust on update. The delta arithmetic is
    -- the reason the rows must be buffered rather than applied one at a time: several
    -- lines of the same order may hit the same stock row in one statement.
    IF INSERTING THEN
      l_delta := :NEW.qty;
    ELSIF DELETING THEN
      l_delta := -:OLD.qty;
    ELSE
      l_delta := NVL(:NEW.qty, 0) - NVL(:OLD.qty, 0);
    END IF;

    IF l_delta <> 0 THEN
      g_n := g_n + 1;
      g_variant(g_n) := CASE WHEN DELETING THEN :OLD.variant_id ELSE :NEW.variant_id END;
      g_loc(g_n)     := CASE WHEN DELETING THEN :OLD.fulfil_location_id
                             ELSE :NEW.fulfil_location_id END;
      g_qty(g_n)     := l_delta;
    END IF;
  END AFTER EACH ROW;

  AFTER STATEMENT IS
  BEGIN
    -- MIGRATION NOTE: same PLS-00678 restriction as trg_cmp_inventory_stock -- no RETURN
    -- inside a compound trigger, so the guard is inverted rather than an early exit.
    IF g_n > 0 THEN
      FORALL i IN 1 .. g_n
        UPDATE inventory_stock
           SET qty_reserved     = GREATEST(NVL(qty_reserved, 0) + g_qty(i), 0)
             , last_movement_ts = SYSTIMESTAMP
         WHERE location_id = g_loc(i)
           AND variant_id  = g_variant(i);

      DBMS_OUTPUT.PUT_LINE('trg_cmp_sales_order_line: ' || g_n
                           || ' reservation deltas applied');
    END IF;
  END AFTER STATEMENT;

END trg_cmp_sales_order_line;
/

CREATE OR REPLACE TRIGGER trg_cmp_loyalty_txn
  FOR INSERT OR UPDATE ON loyalty_transaction
  COMPOUND TRIGGER

  TYPE t_num IS TABLE OF NUMBER INDEX BY PLS_INTEGER;

  g_loyalty t_num;
  g_n       PLS_INTEGER := 0;

  BEFORE STATEMENT IS
  BEGIN
    g_loyalty.DELETE;
    g_n := 0;
  END BEFORE STATEMENT;

  AFTER EACH ROW IS
  BEGIN
    g_n := g_n + 1;
    g_loyalty(g_n) := :NEW.loyalty_id;
  END AFTER EACH ROW;

  AFTER STATEMENT IS
    l_sum     NUMBER;
    l_balance NUMBER;
  BEGIN
    -- This SELECT is the whole reason the trigger is compound: reading
    -- loyalty_transaction from an AFTER EACH ROW section would raise ORA-04091, because
    -- the table is mid-statement. In the AFTER STATEMENT section it is legal.
    --
    -- On PostgreSQL there is no such restriction, so a converter has no signal that this
    -- structure was ever necessary -- and if it flattens the trigger into a row-level
    -- one, the code will work, which is the worst outcome: the pattern gets copied.
    FOR i IN 1 .. g_n LOOP
      SELECT NVL(SUM(points_delta), 0)
        INTO l_sum
        FROM loyalty_transaction
       WHERE loyalty_id = g_loyalty(i);

      SELECT points_balance
        INTO l_balance
        FROM loyalty_account
       WHERE loyalty_id = g_loyalty(i);

      IF l_sum <> l_balance THEN
        INSERT INTO data_quality_issue (issue_id, rule_code, entity_name, entity_key,
                                        severity, detail)
        VALUES (pkg_utils.next_id('SEQ_DQ_ISSUE_ID'), 'LOYALTY_LEDGER_DRIFT',
                'LOYALTY_ACCOUNT', TO_CHAR(g_loyalty(i)), 'WARN',
                'ledger sum ' || l_sum || ' <> account balance ' || l_balance);
      END IF;
    END LOOP;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      NULL;
  END AFTER STATEMENT;

END trg_cmp_loyalty_txn;
/


-- =====================================================================================
-- 22-24 : INSTEAD OF triggers on the updatable views
-- =====================================================================================
-- MIGRATION NOTE (H-27): the trigger case that converts cleanly. PostgreSQL has INSTEAD
-- OF triggers on views with the same name and nearly the same semantics. Two differences
-- to watch. First, the function must RETURN NEW (or OLD on DELETE) or the statement
-- reports zero rows affected and the caller concludes it failed. Second, PostgreSQL
-- forbids a WHEN clause on an INSTEAD OF trigger and requires it to be FOR EACH ROW --
-- both restrictions Oracle does not impose.
-- -------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER trg_io_customer_360
  INSTEAD OF INSERT OR UPDATE OR DELETE ON v_customer_360
  FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO customer (customer_id, customer_ref, first_name, last_name, email,
                          mobile_phone, birth_date, home_country_code,
                          preferred_store_id, primary_address_id, marketing_optin,
                          status, created_ts)
    VALUES (:NEW.customer_id,
            NVL(:NEW.customer_ref, 'CU-PENDING'),
            :NEW.first_name,
            :NEW.last_name,
            LOWER(TRIM(:NEW.email)),
            :NEW.mobile_phone,
            :NEW.birth_date,
            :NEW.home_country_code,
            :NEW.preferred_store_id,
            :NEW.primary_address_id,
            NVL(:NEW.marketing_optin, 'N'),
            NVL(:NEW.customer_status, 'ACTIVE'),
            SYSTIMESTAMP);

    IF :NEW.card_number IS NOT NULL AND :NEW.customer_id IS NOT NULL THEN
      INSERT INTO loyalty_account (loyalty_id, customer_id, card_number, tier_code,
                                   points_balance, lifetime_points, enrolled_date,
                                   status)
      VALUES (pkg_utils.next_id('SEQ_LOYALTY_ID'),
              :NEW.customer_id,
              :NEW.card_number,
              NVL(:NEW.tier_code, 'BRONZE'),
              NVL(:NEW.points_balance, 0),
              NVL(:NEW.lifetime_points, 0),
              TRUNC(SYSDATE),
              'ACTIVE');
    END IF;

  ELSIF UPDATING THEN
    UPDATE customer
       SET first_name         = :NEW.first_name
         , last_name          = :NEW.last_name
         , email              = LOWER(TRIM(:NEW.email))
         , mobile_phone       = :NEW.mobile_phone
         , marketing_optin    = :NEW.marketing_optin
         , preferred_store_id = :NEW.preferred_store_id
         , primary_address_id = :NEW.primary_address_id
         , status             = :NEW.customer_status
     WHERE customer_id = :OLD.customer_id;

    -- The view spans six tables; only two of them are writable through it. Any attempt
    -- to change country_name or tier_name is silently ignored -- deliberately, because
    -- that is what the call-centre screen expects, and worth knowing before somebody
    -- converts it and wonders why those columns look read-only.
    IF :NEW.points_balance IS NOT NULL AND :OLD.loyalty_id IS NOT NULL THEN
      UPDATE loyalty_account
         SET points_balance = :NEW.points_balance
           , tier_code      = NVL(:NEW.tier_code, tier_code)
       WHERE loyalty_id = :OLD.loyalty_id;
    END IF;

  ELSE
    -- GDPR soft delete: the row stays, the identity goes. 'ERASED' is one of the four
    -- values ck_customer_status permits -- worth noting because a converter that renames
    -- or drops a CHECK constraint turns this INSTEAD OF trigger from a guarded operation
    -- into an unguarded one, and nothing about the trigger text changes.
    UPDATE customer
       SET status          = 'ERASED'
         , email           = NULL
         , mobile_phone    = NULL
         , gdpr_erasure_ts = SYSTIMESTAMP
     WHERE customer_id = :OLD.customer_id;
  END IF;
END trg_io_customer_360;
/

CREATE OR REPLACE TRIGGER trg_io_product_sellable
  INSTEAD OF INSERT OR UPDATE OR DELETE ON v_product_sellable
  FOR EACH ROW
DECLARE
  l_product_id NUMBER;
BEGIN
  IF INSERTING THEN
    l_product_id := NVL(:NEW.product_id, pkg_utils.next_id('SEQ_PRODUCT_ID'));

    INSERT INTO product (product_id, sku, product_name, category_id, brand_id,
                         unit_cost, list_price, base_uom, weight_kg, status,
                         launch_date, channel_availability)
    VALUES (l_product_id,
            :NEW.sku,
            :NEW.product_name,
            :NEW.category_id,
            :NEW.brand_id,
            NVL(:NEW.unit_cost, 0),
            NVL(:NEW.list_price, 0),
            NVL(:NEW.base_uom, 'EA'),
            :NEW.weight_kg,
            NVL(:NEW.product_status, 'DRAFT'),
            :NEW.launch_date,
            :NEW.channel_availability);

    INSERT INTO product_variant (variant_id, product_id, variant_sku, barcode_ean13,
                                 size_code, colour_code, pack_qty, is_active)
    VALUES (NVL(:NEW.variant_id, pkg_utils.next_id('SEQ_VARIANT_ID')),
            l_product_id,
            :NEW.variant_sku,
            :NEW.barcode_ean13,
            :NEW.size_code,
            :NEW.colour_code,
            NVL(:NEW.pack_qty, 1),
            NVL(:NEW.variant_active, 'Y'));

  ELSIF UPDATING THEN
    UPDATE product
       SET product_name = :NEW.product_name
         , list_price   = :NEW.list_price
         , unit_cost    = :NEW.unit_cost
         , status       = :NEW.product_status
         , weight_kg    = :NEW.weight_kg
     WHERE product_id = :OLD.product_id;

    UPDATE product_variant
       SET is_active     = :NEW.variant_active
         , barcode_ean13 = :NEW.barcode_ean13
         , pack_qty      = :NEW.pack_qty
     WHERE variant_id = :OLD.variant_id;

  ELSE
    UPDATE product_variant SET is_active = 'N' WHERE variant_id = :OLD.variant_id;
  END IF;
END trg_io_product_sellable;
/

CREATE OR REPLACE TRIGGER trg_io_open_purchase_orders
  INSTEAD OF INSERT OR UPDATE OR DELETE ON v_open_purchase_orders
  FOR EACH ROW
DECLARE
  l_po_id NUMBER;
BEGIN
  IF INSERTING THEN
    l_po_id := NVL(:NEW.po_id, pkg_utils.next_id('SEQ_PO_ID'));

    INSERT INTO purchase_order (po_id, po_number, supplier_id, warehouse_id,
                                order_date, expected_date, status, currency_code,
                                order_total, approved_by_employee_id)
    VALUES (l_po_id,
            NVL(:NEW.po_number, 'PO' || LPAD(TO_CHAR(l_po_id), 12, '0')),
            :NEW.supplier_id,
            :NEW.warehouse_id,
            NVL(:NEW.order_date, TRUNC(SYSDATE)),
            NVL(:NEW.expected_date, TRUNC(SYSDATE) + 14),
            NVL(:NEW.status, 'DRAFT'),
            :NEW.currency_code,
            NVL(:NEW.order_total, 0),
            :NEW.approved_by_employee_id);

  ELSIF UPDATING THEN
    -- Routed through the package rather than issued inline, so the state machine and its
    -- user-defined exceptions (H-28) stay in one place. An INSTEAD OF trigger calling
    -- business logic is common and converts fine; the exceptions it can raise are the
    -- part that needs the SQLCODE-to-SQLSTATE mapping.
    IF :NEW.status = 'SENT' AND :OLD.status <> 'SENT' THEN
      pkg_purchasing.send_po(:OLD.po_id);
    ELSIF :NEW.status = 'CANCELLED' AND :OLD.status <> 'CANCELLED' THEN
      pkg_purchasing.cancel_po(:OLD.po_id, 'VIEW_UPDATE');
    ELSE
      UPDATE purchase_order
         SET expected_date           = :NEW.expected_date
           , approved_by_employee_id = :NEW.approved_by_employee_id
       WHERE po_id = :OLD.po_id;
    END IF;

  ELSE
    pkg_purchasing.cancel_po(:OLD.po_id, 'VIEW_DELETE');
  END IF;
END trg_io_open_purchase_orders;
/


-- =====================================================================================
-- 25-26 : the remaining row triggers
-- =====================================================================================

CREATE OR REPLACE TRIGGER trg_ad_coupon_audit
  AFTER DELETE ON coupon
  FOR EACH ROW
DECLARE
  -- MIGRATION NOTE (H-01): a typed NULL, not a bare one. pkg_audit.write_audit is
  -- overloaded on VARCHAR2 and CLOB and an untyped NULL is a candidate for both, which
  -- Oracle rejects as PLS-00307 -- the same ambiguity PostgreSQL will raise as
  -- "function is not unique" at far more call sites after conversion.
  l_new_row VARCHAR2(1) := NULL;
BEGIN
  -- MIGRATION NOTE (H-02): the autonomous audit call from a DELETE trigger is the clearest
  -- statement of the problem. A deleted coupon must leave a trace even if the enclosing
  -- transaction rolls back -- that is the whole reason pkg_audit is autonomous. Convert it
  -- to an in-transaction INSERT and the trace vanishes with the rollback; convert it to a
  -- dblink call and you open a connection per deleted coupon. Neither is free, and the
  -- decision belongs to the business, not the converter.
  pkg_audit.write_audit('COUPON',
                        TO_CHAR(:OLD.coupon_id),
                        'D',
                        :OLD.coupon_code || '|promo=' || TO_CHAR(:OLD.promotion_id)
                          || '|redemptions=' || TO_CHAR(:OLD.redemption_count),
                        l_new_row);
END trg_ad_coupon_audit;
/

CREATE OR REPLACE TRIGGER trg_au_order_payment
  AFTER UPDATE ON order_payment
  FOR EACH ROW
  WHEN (NEW.status <> OLD.status)
BEGIN
  -- MIGRATION NOTE (T-05 / H-31): NVL, not DECODE. DECODE is a SQL function and Oracle
  -- rejects it in a PL/SQL expression with PLS-00204 -- it is only legal inside a SQL
  -- statement. That restriction is easy to forget when converting, because orafce
  -- provides decode() as an ordinary PostgreSQL function callable from PL/pgSQL, so the
  -- converted code can end up *more* permissive than the original. NVL converts to
  -- COALESCE, with the usual caveat that NVL evaluates both arguments and COALESCE
  -- short-circuits.
  pkg_audit.write_audit('ORDER_PAYMENT',
                        TO_CHAR(:OLD.payment_id),
                        'U',
                        NVL(:OLD.status, 'UNKNOWN'),
                        NVL(:NEW.status, 'UNKNOWN'));

  IF :NEW.status = 'CAPTURED' AND :OLD.status <> 'CAPTURED' THEN
    UPDATE sales_order
       SET status = 'PLACED'
     WHERE order_id = :NEW.order_id
       AND status   = 'CART';
  END IF;
END trg_au_order_payment;
/


-- =====================================================================================
-- Summary
-- =====================================================================================
DECLARE
  l_triggers PLS_INTEGER;
  l_invalid  PLS_INTEGER;
  l_disabled PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO l_triggers
    FROM user_triggers WHERE trigger_name NOT LIKE '%GEN%';

  SELECT COUNT(*) INTO l_invalid
    FROM user_objects WHERE object_type = 'TRIGGER' AND status = 'INVALID';

  SELECT COUNT(*) INTO l_disabled
    FROM user_triggers WHERE status <> 'ENABLED';

  DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('09-triggers.sql summary');
  DBMS_OUTPUT.PUT_LINE('  hand-written triggers : ' || l_triggers || ' (design target 26)');
  DBMS_OUTPUT.PUT_LINE('  INVALID               : ' || l_invalid || ' (must be 0)');
  DBMS_OUTPUT.PUT_LINE('  DISABLED              : ' || l_disabled || ' (must be 0)');
  DBMS_OUTPUT.PUT_LINE('  each of these becomes TWO PostgreSQL objects -- see H-25');
  DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------');
END;
/

PROMPT 09-triggers.sql complete.

